-- Flamingos Community Voting
-- Run once in the Supabase SQL editor, then redeploy the community-gallery function.

CREATE TABLE IF NOT EXISTS community_gallery_votes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submission_id UUID NOT NULL REFERENCES community_gallery_submissions(id) ON DELETE CASCADE,
  voter_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT community_gallery_votes_one_per_artwork UNIQUE (submission_id, voter_hash)
);

CREATE INDEX IF NOT EXISTS idx_community_gallery_votes_submission
  ON community_gallery_votes (submission_id);

ALTER TABLE community_gallery_votes ENABLE ROW LEVEL SECURITY;
